name: Build Windows

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Build
        run: cargo build --release -p repak_cli

      - name: Upload repak.exe
        uses: actions/upload-artifact@v4
        with:
          name: repak-windows-x64
          path: target/release/repak.exe
